# Generated by Django 6.0.3 on 2026-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='教师编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='职称')),
                ('department', models.CharField(max_length=100, verbose_name='所属院系')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teachers',
            },
        ),
    ]
