# Generated by Django 6.0.3 on 2026-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True, verbose_name='课程编号')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('credit', models.PositiveIntegerField(verbose_name='学分')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
            },
        ),
    ]
